 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Airline;
import Business.*;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import java.awt.Component;
/**
 *
 * @author xutao
 */
public class ViewFlightJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAirlineJPanel
     */
    private Flight flight = new Flight();
    private JPanel container = new JPanel();
    private AirLine airline = new AirLine();
    public ViewFlightJPanel( Flight flight, JPanel container, AirLine airline) {
        initComponents();
        this.flight = flight;
        this.container = container;
        this.airline = airline;
        Display();
        saveBtn.setEnabled(false);
        updateBtn.setEnabled(true);
        
    }
    
    public void Display() {
        idTextField.setText(String.valueOf(flight.getIdNumber()));
        departureTextField.setText(flight.getDeparture());
        destinationTextField.setText(flight.getDestination());
        int date = flight.getDepDate();
        int yy = date / 10000;
        int mm = date / 100 - yy * 100;
        int dd = date - yy * 10000 - mm * 100;
        String yyString ;
        String mmString;
        String ddString;
        if( yy / 10 == 0)
            yyString = "0" + String.valueOf(yy);
        else
            yyString = String.valueOf(yy);
        if( mm / 10 == 0)
            mmString = "0" + String.valueOf(mm);
        else
             mmString = String.valueOf(mm);
        if( dd / 10 == 0)
            ddString = "0" + String.valueOf(dd);
        else
            ddString = String.valueOf(dd);
        String dateString = yyString + "/" + mmString + "/" + ddString;
        depDateTextField.setText(dateString);
        int time = flight.getDepTime();
        int hh = time / 100;
        int mi = time - hh * 100;
        String hhString;
        String miString;
        if( hh / 10 == 0)
            hhString = "0" + String.valueOf(hh);
        else
            hhString = String.valueOf(hh);
        if( mi / 10 == 0)
            miString = "0" + String.valueOf(mi);
        else
            miString = String.valueOf(mi);
        String timeString = hhString + ":" + miString;
        depTimeTextField.setText(timeString);
        serialNumTextField.setText(String.valueOf(flight.getAirplane().getSerialNumber()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        serialNumTextField = new javax.swing.JTextField();
        depTimeTextField = new javax.swing.JTextField();
        depDateTextField = new javax.swing.JTextField();
        destinationTextField = new javax.swing.JTextField();
        departureTextField = new javax.swing.JTextField();
        idTextField = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("View Flight Details");

        jLabel2.setText("Flight ID Number :");

        jLabel3.setText("Departure :");

        jLabel4.setText("Destination :");

        jLabel5.setText("Departure Date :");

        jLabel6.setText("Departure Time :");

        jLabel7.setText("Airplane Serial Number :");

        serialNumTextField.setEditable(false);
        serialNumTextField.setEnabled(false);

        depTimeTextField.setEditable(false);
        depTimeTextField.setEnabled(false);

        depDateTextField.setEditable(false);
        depDateTextField.setEnabled(false);

        destinationTextField.setEditable(false);
        destinationTextField.setEnabled(false);

        departureTextField.setEditable(false);
        departureTextField.setEnabled(false);

        idTextField.setEditable(false);
        idTextField.setEnabled(false);

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        backBtn.setText("< < back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveBtn)
                        .addGap(18, 18, 18)
                        .addComponent(updateBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(backBtn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addComponent(departureTextField)
                            .addComponent(destinationTextField)
                            .addComponent(depDateTextField)
                            .addComponent(depTimeTextField)
                            .addComponent(serialNumTextField))))
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(departureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(destinationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(depDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(depTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(serialNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(updateBtn))
                .addGap(18, 18, 18)
                .addComponent(backBtn)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
        
        Component [] component = container.getComponents();
        for ( Component cp : component) {
            if ( cp instanceof ManageFlightJPanel) {
                ManageFlightJPanel mfJP = (ManageFlightJPanel) cp;
                mfJP.PopulateTable();
            }
        }
        
    }//GEN-LAST:event_backBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        
        idTextField.setEnabled(true);
        idTextField.setEditable(true);
        departureTextField.setEnabled(true);
        departureTextField.setEditable(true);
        destinationTextField.setEnabled(true);
        destinationTextField.setEditable(true);
        depDateTextField.setEnabled(true);
        depDateTextField.setEditable(true);
        depTimeTextField.setEnabled(true);
        depTimeTextField.setEditable(true);
        serialNumTextField.setEnabled(true);
        serialNumTextField.setEditable(true);
        saveBtn.setEnabled(true);
        updateBtn.setEnabled(false);
        Display();
        
    }//GEN-LAST:event_updateBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
         // TODO add your handling code here:
        //check the input data
        if ( idTextField.getText().isEmpty() || departureTextField.getText().isEmpty() || destinationTextField.getText().isEmpty() ||
                depDateTextField.getText().isEmpty() || depTimeTextField.getText().isEmpty() || serialNumTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter every field!","Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            Integer.parseInt(idTextField.getText());
            Integer.parseInt(serialNumTextField.getText());
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please enter valid data!!","Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        flight.setIdNumber(Integer.parseInt(idTextField.getText()));
        flight.setDeparture(departureTextField.getText());
        flight.setDestination(destinationTextField.getText());
        
        String dateString = depDateTextField.getText().replace("/", "");
        String timeString = depTimeTextField.getText().replace(":", "");
        
        if ( !dateString.equals( String.valueOf(flight.getDepDate())) ) {
            try {
                Integer.parseInt(depDateTextField.getText());
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Please enter valid Date imformation !");
                return;
            }
            if ( depDateTextField.getText().length() >= 6  ){
                JOptionPane.showMessageDialog(null, "Please enter right time format!!","Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            flight.setDepDate(Integer.parseInt(depDateTextField.getText()));
        }
        
        if( !timeString.replace(":", "").equals( String.valueOf(flight.getDepTime())) ) {
            try {
                Integer.parseInt(depTimeTextField.getText());
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Please enter valid Time imformation !");
                return;
            }
            if (  depTimeTextField.getText().length() != 4 ){
                JOptionPane.showMessageDialog(null, "Please enter right time format!!","Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            flight.setDepTime(Integer.parseInt(depTimeTextField.getText()));
        }
        
        
        
        if ( Integer.parseInt(serialNumTextField.getText()) != flight.getAirplane().getSerialNumber() ) {
            if ( airline.SearchAirplane(Integer.parseInt(serialNumTextField.getText())) != null)
                flight.setAirplane(airline.SearchAirplane(Integer.parseInt(serialNumTextField.getText())));
            else {
                JOptionPane.showMessageDialog(null, "No such an airplane, Please add the airplane first!", "Warining", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        
        JOptionPane.showMessageDialog(null, "Update Successfully !");
        
        
        idTextField.setEnabled(false);
        idTextField.setEditable(false);
        departureTextField.setEnabled(false);
        departureTextField.setEditable(false);
        destinationTextField.setEnabled(false);
        destinationTextField.setEditable(false);
        depDateTextField.setEnabled(false);
        depDateTextField.setEditable(false);
        depTimeTextField.setEnabled(false);
        depTimeTextField.setEditable(false);
        serialNumTextField.setEnabled(false);
        serialNumTextField.setEditable(false);
        saveBtn.setEnabled(false);
        updateBtn.setEnabled(true);
    }//GEN-LAST:event_saveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField depDateTextField;
    private javax.swing.JTextField depTimeTextField;
    private javax.swing.JTextField departureTextField;
    private javax.swing.JTextField destinationTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField serialNumTextField;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
