/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Individual.Person;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author 徐涛
 */
public class ReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportJPanel
     */
    public ReportJPanel(Person person) {
        initComponents();
        DisplayReport(person);
    }
    
    public void DisplayReport(Person person) {
        
        // DomeInfo
        firstNameTextField.setText(person.getDemoInfo().getFirstName());
        lastNameTextField.setText(person.getDemoInfo().getLastName());
        phoneNumberTextField.setText(person.getDemoInfo().getPhoneNum());
        dateOfBirthTextField.setText(person.getDemoInfo().getDateOfBirth());
        ageTextField.setText(person.getDemoInfo().getAge());
        hightTextField.setText(person.getDemoInfo().getHight());
        weightTextField.setText(person.getDemoInfo().getWeight());
        ssnTextField.setText(person.getDemoInfo().getSsn());
        
        // Address Info
        street1TextField.setText(person.getAddressInfo().getStreet1());
        street2TextField.setText(person.getAddressInfo().getStreet2());
        cityTextField.setText(person.getAddressInfo().getCity());
        stateTextField.setText(person.getAddressInfo().getState());
        zipCodeTextField.setText(person.getAddressInfo().getZipCode());
        
        // DriverLicense
        licenseNumTextField.setText(person.getDriverLicenseInfo().getLicenseNum());
        issueDateTextField.setText(person.getDriverLicenseInfo().getIssueDate());
        dateOfExpirationTextField.setText(person.getDriverLicenseInfo().getDateOfExpiration());
        bloodTypeTextField.setText(person.getDriverLicenseInfo().getBloodType());
        
        String path = person.getDriverLicenseInfo().getPictureAdd();
        ImageIcon icon=new ImageIcon(path); 
        icon.setImage(icon.getImage().getScaledInstance(73, 99, Image.SCALE_DEFAULT));
        photo.setIcon(icon);
        
        //Saving Account Info
        sBankNameTextField.setText(person.getSavingAccountInfo().getBankName());
        sRountingNumTextField.setText(person.getSavingAccountInfo().getBankRoutingNum());
        sAccountNumTextField.setText(person.getSavingAccountInfo().getBankAccountNum());
        sAccountBalanceTextField.setText(person.getSavingAccountInfo().getAccountBalance());
        sAccountTypeTextField.setText(person.getSavingAccountInfo().getAccountType());
        
        // Checking Account Info
        cBankNameTextField.setText(person.getCheckingAccountInfo().getBankName());
        cRountingNumTextField.setText(person.getCheckingAccountInfo().getBankRoutingNum());
        cAccountNumTextField.setText(person.getCheckingAccountInfo().getBankAccountNum());
        cAccountBalanceTextField.setText(person.getCheckingAccountInfo().getAccountBalance());
        cAccountTypeTextField.setText(person.getCheckingAccountInfo().getAccountType());
        
        //Medical Record
        medicalRecordNumTextField.setText(person.getMedicalRecord().getMedicalRecordNum());
        alergy1TextField.setText(person.getMedicalRecord().getAlergy1());
        alergy2TextField.setText(person.getMedicalRecord().getAlergy2());
        alergy3TextField.setText(person.getMedicalRecord().getAlergy3());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        demoInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        phoneNumberTextField = new javax.swing.JTextField();
        dateOfBirthTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        hightTextField = new javax.swing.JTextField();
        weightTextField = new javax.swing.JTextField();
        ssnTextField = new javax.swing.JTextField();
        addressInfo = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        street1TextField = new javax.swing.JTextField();
        street2TextField = new javax.swing.JTextField();
        cityTextField = new javax.swing.JTextField();
        stateTextField = new javax.swing.JTextField();
        zipCodeTextField = new javax.swing.JTextField();
        driverLicense = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        licenseNumTextField = new javax.swing.JTextField();
        issueDateTextField = new javax.swing.JTextField();
        dateOfExpirationTextField = new javax.swing.JTextField();
        bloodTypeTextField = new javax.swing.JTextField();
        photo = new javax.swing.JLabel();
        savingAccount = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        sBankNameTextField = new javax.swing.JTextField();
        sAccountNumTextField = new javax.swing.JTextField();
        sRountingNumTextField = new javax.swing.JTextField();
        sAccountBalanceTextField = new javax.swing.JTextField();
        sAccountTypeTextField = new javax.swing.JTextField();
        checkingAccount = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        cBankNameTextField = new javax.swing.JTextField();
        cAccountNumTextField = new javax.swing.JTextField();
        cRountingNumTextField = new javax.swing.JTextField();
        cAccountBalanceTextField = new javax.swing.JTextField();
        cAccountTypeTextField = new javax.swing.JTextField();
        medicalPecord = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        medicalRecordNumTextField = new javax.swing.JTextField();
        alergy1TextField = new javax.swing.JTextField();
        alergy2TextField = new javax.swing.JTextField();
        alergy3TextField = new javax.swing.JTextField();

        demoInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Demographic Info"));

        jLabel1.setText("First Name:");

        jLabel2.setText("Last Name:");

        jLabel3.setText("Phone Number:");

        jLabel4.setText("Date of Birth:");

        jLabel5.setText("Age:");

        jLabel6.setText("Hight:");

        jLabel7.setText("Weight:");

        jLabel8.setText("ssn:");

        firstNameTextField.setEditable(false);
        firstNameTextField.setEnabled(false);

        lastNameTextField.setEditable(false);
        lastNameTextField.setEnabled(false);

        phoneNumberTextField.setEditable(false);
        phoneNumberTextField.setEnabled(false);

        dateOfBirthTextField.setEditable(false);
        dateOfBirthTextField.setEnabled(false);

        ageTextField.setEditable(false);
        ageTextField.setEnabled(false);

        hightTextField.setEditable(false);
        hightTextField.setEnabled(false);

        weightTextField.setEditable(false);
        weightTextField.setEnabled(false);

        ssnTextField.setEditable(false);
        ssnTextField.setEnabled(false);

        javax.swing.GroupLayout demoInfoLayout = new javax.swing.GroupLayout(demoInfo);
        demoInfo.setLayout(demoInfoLayout);
        demoInfoLayout.setHorizontalGroup(
            demoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(demoInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(demoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(demoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateOfBirthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ssnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        demoInfoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ageTextField, dateOfBirthTextField, firstNameTextField, hightTextField, lastNameTextField, phoneNumberTextField, ssnTextField, weightTextField});

        demoInfoLayout.setVerticalGroup(
            demoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(demoInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(demoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(demoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(demoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(demoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dateOfBirthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(demoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(demoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(hightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(demoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(weightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(demoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ssnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addressInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Address Info"));

        jLabel9.setText("Street1:");

        jLabel10.setText("Street2:");

        jLabel11.setText("City:");

        jLabel12.setText("State:");

        jLabel13.setText("ZipCode:");

        street1TextField.setEditable(false);
        street1TextField.setEnabled(false);

        street2TextField.setEditable(false);
        street2TextField.setEnabled(false);
        street2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                street2TextFieldActionPerformed(evt);
            }
        });

        cityTextField.setEditable(false);
        cityTextField.setEnabled(false);

        stateTextField.setEditable(false);
        stateTextField.setEnabled(false);

        zipCodeTextField.setEditable(false);
        zipCodeTextField.setEnabled(false);
        zipCodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipCodeTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addressInfoLayout = new javax.swing.GroupLayout(addressInfo);
        addressInfo.setLayout(addressInfoLayout);
        addressInfoLayout.setHorizontalGroup(
            addressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(28, 28, 28)
                .addGroup(addressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(street1TextField)
                    .addComponent(street2TextField)
                    .addComponent(cityTextField)
                    .addComponent(stateTextField)
                    .addComponent(zipCodeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                .addContainerGap())
        );
        addressInfoLayout.setVerticalGroup(
            addressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(street1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(addressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(street2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(addressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(addressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(stateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(addressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(zipCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        driverLicense.setBorder(javax.swing.BorderFactory.createTitledBorder("Driver License"));
        driverLicense.setPreferredSize(new java.awt.Dimension(266, 361));

        jLabel14.setText("License Number:");

        jLabel15.setText("Date of Issue:");

        jLabel16.setText("Expiration Date:");

        jLabel17.setText("Blood Type:");

        jLabel18.setText("Photo:");

        licenseNumTextField.setEditable(false);
        licenseNumTextField.setEnabled(false);

        issueDateTextField.setEditable(false);
        issueDateTextField.setEnabled(false);

        dateOfExpirationTextField.setEditable(false);
        dateOfExpirationTextField.setEnabled(false);

        bloodTypeTextField.setEditable(false);
        bloodTypeTextField.setEnabled(false);

        javax.swing.GroupLayout driverLicenseLayout = new javax.swing.GroupLayout(driverLicense);
        driverLicense.setLayout(driverLicenseLayout);
        driverLicenseLayout.setHorizontalGroup(
            driverLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(driverLicenseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(driverLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(driverLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(licenseNumTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(issueDateTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(dateOfExpirationTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(bloodTypeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addGroup(driverLicenseLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        driverLicenseLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bloodTypeTextField, dateOfExpirationTextField, issueDateTextField, licenseNumTextField});

        driverLicenseLayout.setVerticalGroup(
            driverLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(driverLicenseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(driverLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(licenseNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(driverLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(issueDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(driverLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(dateOfExpirationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(driverLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(bloodTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(driverLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(driverLicenseLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel18)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, driverLicenseLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        savingAccount.setBorder(javax.swing.BorderFactory.createTitledBorder("Saving Account"));

        jLabel19.setText("Bank Name:");

        jLabel20.setText("Account Number:");

        jLabel21.setText("Rounting Number:");

        jLabel22.setText("Account Balance:");

        jLabel23.setText("Account Type:");

        sBankNameTextField.setEditable(false);
        sBankNameTextField.setEnabled(false);

        sAccountNumTextField.setEditable(false);
        sAccountNumTextField.setEnabled(false);

        sRountingNumTextField.setEditable(false);
        sRountingNumTextField.setEnabled(false);
        sRountingNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sRountingNumTextFieldActionPerformed(evt);
            }
        });

        sAccountBalanceTextField.setEditable(false);
        sAccountBalanceTextField.setEnabled(false);

        sAccountTypeTextField.setEditable(false);
        sAccountTypeTextField.setEnabled(false);

        javax.swing.GroupLayout savingAccountLayout = new javax.swing.GroupLayout(savingAccount);
        savingAccount.setLayout(savingAccountLayout);
        savingAccountLayout.setHorizontalGroup(
            savingAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(savingAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(savingAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(savingAccountLayout.createSequentialGroup()
                        .addGroup(savingAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(savingAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sAccountNumTextField)
                            .addComponent(sBankNameTextField)))
                    .addGroup(savingAccountLayout.createSequentialGroup()
                        .addGroup(savingAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(savingAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sAccountTypeTextField)
                            .addComponent(sAccountBalanceTextField)
                            .addComponent(sRountingNumTextField)))))
        );
        savingAccountLayout.setVerticalGroup(
            savingAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(savingAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(savingAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(sBankNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(savingAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(sAccountNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(savingAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(sRountingNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(savingAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(sAccountBalanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(savingAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(sAccountTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        checkingAccount.setBorder(javax.swing.BorderFactory.createTitledBorder("Checkinging Account"));

        jLabel24.setText("Bank Name:");

        jLabel25.setText("Account Number:");

        jLabel26.setText("Rounting Number:");

        jLabel27.setText("Account Balance:");

        jLabel28.setText("Account Type:");

        cBankNameTextField.setEditable(false);
        cBankNameTextField.setEnabled(false);

        cAccountNumTextField.setEditable(false);
        cAccountNumTextField.setEnabled(false);

        cRountingNumTextField.setEditable(false);
        cRountingNumTextField.setEnabled(false);

        cAccountBalanceTextField.setEditable(false);
        cAccountBalanceTextField.setEnabled(false);

        cAccountTypeTextField.setEditable(false);
        cAccountTypeTextField.setEnabled(false);

        javax.swing.GroupLayout checkingAccountLayout = new javax.swing.GroupLayout(checkingAccount);
        checkingAccount.setLayout(checkingAccountLayout);
        checkingAccountLayout.setHorizontalGroup(
            checkingAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkingAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(checkingAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkingAccountLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cBankNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(checkingAccountLayout.createSequentialGroup()
                        .addGroup(checkingAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(checkingAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cAccountTypeTextField)
                            .addComponent(cAccountBalanceTextField)
                            .addComponent(cRountingNumTextField)
                            .addComponent(cAccountNumTextField)))))
        );
        checkingAccountLayout.setVerticalGroup(
            checkingAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkingAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(checkingAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(cBankNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(checkingAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(cAccountNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(checkingAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(cRountingNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(checkingAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(cAccountBalanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(checkingAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(cAccountTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        medicalPecord.setBorder(javax.swing.BorderFactory.createTitledBorder("Medical Record"));
        medicalPecord.setPreferredSize(new java.awt.Dimension(266, 299));

        jLabel29.setText("Record Number:");

        jLabel30.setText("Alergy1:");

        jLabel31.setText("Alergy2:");

        jLabel32.setText("Alergy3:");

        medicalRecordNumTextField.setEditable(false);
        medicalRecordNumTextField.setEnabled(false);

        alergy1TextField.setEditable(false);
        alergy1TextField.setEnabled(false);

        alergy2TextField.setEditable(false);
        alergy2TextField.setEnabled(false);

        alergy3TextField.setEditable(false);
        alergy3TextField.setEnabled(false);

        javax.swing.GroupLayout medicalPecordLayout = new javax.swing.GroupLayout(medicalPecord);
        medicalPecord.setLayout(medicalPecordLayout);
        medicalPecordLayout.setHorizontalGroup(
            medicalPecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medicalPecordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(medicalPecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(medicalPecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(medicalRecordNumTextField)
                    .addComponent(alergy1TextField)
                    .addComponent(alergy2TextField)
                    .addComponent(alergy3TextField)))
        );
        medicalPecordLayout.setVerticalGroup(
            medicalPecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medicalPecordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(medicalPecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(medicalRecordNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(medicalPecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(alergy1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(medicalPecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(alergy2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(medicalPecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(alergy3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(savingAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(demoInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addressInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkingAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(driverLicense, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addComponent(medicalPecord, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(demoInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(addressInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(driverLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(medicalPecord, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(checkingAccount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(savingAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void street2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_street2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_street2TextFieldActionPerformed

    private void zipCodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipCodeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipCodeTextFieldActionPerformed

    private void sRountingNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sRountingNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sRountingNumTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addressInfo;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JTextField alergy1TextField;
    private javax.swing.JTextField alergy2TextField;
    private javax.swing.JTextField alergy3TextField;
    private javax.swing.JTextField bloodTypeTextField;
    private javax.swing.JTextField cAccountBalanceTextField;
    private javax.swing.JTextField cAccountNumTextField;
    private javax.swing.JTextField cAccountTypeTextField;
    private javax.swing.JTextField cBankNameTextField;
    private javax.swing.JTextField cRountingNumTextField;
    private javax.swing.JPanel checkingAccount;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JTextField dateOfBirthTextField;
    private javax.swing.JTextField dateOfExpirationTextField;
    private javax.swing.JPanel demoInfo;
    private javax.swing.JPanel driverLicense;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JTextField hightTextField;
    private javax.swing.JTextField issueDateTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JTextField licenseNumTextField;
    private javax.swing.JPanel medicalPecord;
    private javax.swing.JTextField medicalRecordNumTextField;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JLabel photo;
    private javax.swing.JTextField sAccountBalanceTextField;
    private javax.swing.JTextField sAccountNumTextField;
    private javax.swing.JTextField sAccountTypeTextField;
    private javax.swing.JTextField sBankNameTextField;
    private javax.swing.JTextField sRountingNumTextField;
    private javax.swing.JPanel savingAccount;
    private javax.swing.JTextField ssnTextField;
    private javax.swing.JTextField stateTextField;
    private javax.swing.JTextField street1TextField;
    private javax.swing.JTextField street2TextField;
    private javax.swing.JTextField weightTextField;
    private javax.swing.JTextField zipCodeTextField;
    // End of variables declaration//GEN-END:variables
}
