/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.customer;
import Business.*;
import javax.swing.JPanel;
import java.awt.CardLayout;

/**
 *
 * @author xutao
 */
public class FlightDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FlightDetailsJPanel
     */
    private TravelAgency travelAgency;
    private JPanel container;
    private Flight flight;
    public FlightDetailsJPanel(TravelAgency travelAgency, JPanel container, Flight flight) {
        
        initComponents();
        this.travelAgency = travelAgency;
        this.container = container;
        this.flight = flight;
        Display();
        
    }
    
    public void Display() {
        idTextField.setText(String.valueOf(flight.getIdNumber()));
        departureTextField.setText(flight.getDeparture());
        destinationTextField.setText(flight.getDestination());
        
        int date = flight.getDepDate();
        int time = flight.getDepTime();
        String zero = "0";
        String dateString = "";
        String timeString = "";
        int yy = date / 10000;
        if ( yy / 10 == 0 )
            dateString = zero + String.valueOf(yy);
        else
            dateString = String.valueOf(yy);
        int mm = date / 100 - yy * 100;
        if (mm / 10 == 0)
            dateString += "/" +zero + String.valueOf(mm);
        else 
            dateString += "/" + String.valueOf(mm);
        int dd = date - yy * 10000 - mm * 100;
        if ( dd / 10 == 0 )
            dateString += "/" + zero + String.valueOf(dd);
        else 
            dateString += "/" + String.valueOf(dd);
        depDateTextField.setText(dateString);
        
        int hour = time / 100;
        if ( hour / 10 == 0 )
            timeString += zero + String.valueOf(hour);
        else 
            timeString += String.valueOf(hour);
        int minute = time - hour * 100;
        if ( minute / 10 == 0)
            timeString += ":" + zero + String.valueOf(minute);
        else 
            timeString += ":" + String.valueOf(minute);
        depTimeTextField.setText(timeString);
        serialNumTextField.setText(String.valueOf(flight.getAirplane().getSerialNumber()));
        seatTextField.setText(String.valueOf(flight.getSeat().getAvailNum()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        seatTextField = new javax.swing.JTextField();
        serialNumTextField = new javax.swing.JTextField();
        depTimeTextField = new javax.swing.JTextField();
        depDateTextField = new javax.swing.JTextField();
        destinationTextField = new javax.swing.JTextField();
        departureTextField = new javax.swing.JTextField();
        idTextField = new javax.swing.JTextField();
        bookTextField = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Flight Details");

        jLabel2.setText("Flight ID Number :");

        jLabel3.setText("Departure :");

        jLabel4.setText("Destination :");

        jLabel5.setText("Departure Date :");

        jLabel6.setText("Departure Time :");

        jLabel7.setText("Airplane Serial Number :");

        jLabel8.setText("Available Seat Quantity :");

        seatTextField.setEditable(false);
        seatTextField.setEnabled(false);

        serialNumTextField.setEditable(false);
        serialNumTextField.setEnabled(false);
        serialNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialNumTextFieldActionPerformed(evt);
            }
        });

        depTimeTextField.setEditable(false);
        depTimeTextField.setEnabled(false);

        depDateTextField.setEditable(false);
        depDateTextField.setEnabled(false);

        destinationTextField.setEditable(false);
        destinationTextField.setEnabled(false);

        departureTextField.setEditable(false);
        departureTextField.setEnabled(false);

        idTextField.setEditable(false);
        idTextField.setEnabled(false);

        bookTextField.setText("Book it !");
        bookTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookTextFieldActionPerformed(evt);
            }
        });

        backBtn.setText(" < < back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backBtn)
                                .addGap(256, 256, 256)
                                .addComponent(bookTextField))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addComponent(seatTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(idTextField)
                                        .addComponent(departureTextField)
                                        .addComponent(destinationTextField)
                                        .addComponent(depDateTextField)
                                        .addComponent(depTimeTextField)
                                        .addComponent(serialNumTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)))))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(departureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(destinationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(depDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(depTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(serialNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(seatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookTextField)
                    .addComponent(backBtn))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void serialNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serialNumTextFieldActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backBtnActionPerformed

    private void bookTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookTextFieldActionPerformed
        // TODO add your handling code here:
        BookingJPanel bJP = new BookingJPanel(travelAgency, container, flight);
        container.add("BookingJPanel",bJP);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
        
    }//GEN-LAST:event_bookTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton bookTextField;
    private javax.swing.JTextField depDateTextField;
    private javax.swing.JTextField depTimeTextField;
    private javax.swing.JTextField departureTextField;
    private javax.swing.JTextField destinationTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField seatTextField;
    private javax.swing.JTextField serialNumTextField;
    // End of variables declaration//GEN-END:variables
}
