/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.customer;
import Business.*;
import javax.swing.JPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import java.util.ArrayList;


/**
 *
 * @author xutao
 */
public class SearchConditionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchConditionJPanel
     */
    
    private TravelAgency travelagency = new TravelAgency();
    private JPanel container = new JPanel();
    public SearchConditionJPanel(TravelAgency travelAgency, JPanel container) {
        initComponents();
        this.travelagency = travelAgency;
        this.container = container;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        timeTextField = new javax.swing.JTextField();
        arrivalTextField = new javax.swing.JTextField();
        departureTextField = new javax.swing.JTextField();
        flightNumberTextField = new javax.swing.JTextField();
        dateTextField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        allBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Input your requestment for the Flight");

        jLabel2.setText("Flight Number :");

        jLabel3.setText("Departure Location :");

        jLabel4.setText("Arrival Location :");

        jLabel5.setText("Preferred time of day :");

        jLabel6.setText("Date :");

        arrivalTextField.setText("Beijing");

        departureTextField.setText("Boston");

        searchBtn.setText("Search Flight");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        allBtn.setText("View All");
        allBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(allBtn)
                        .addGap(18, 18, 18)
                        .addComponent(searchBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel1)
                        .addGap(0, 33, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(flightNumberTextField)
                            .addComponent(departureTextField)
                            .addComponent(arrivalTextField)
                            .addComponent(timeTextField)
                            .addComponent(dateTextField))))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(flightNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(departureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(arrivalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(timeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBtn)
                    .addComponent(allBtn))
                .addContainerGap(101, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        if (departureTextField.getText().isEmpty() || arrivalTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "the departure location and arrival loction can't be empty!");
            return;
        }
        try {
            if( !flightNumberTextField.getText().isEmpty() )
                Integer.parseInt(flightNumberTextField.getText());
            if(!dateTextField.getText().isEmpty())
                Integer.parseInt(dateTextField.getText());
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "the flight number and date must be number!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if ( !timeTextField.getText().equals("morning") &&  !timeTextField.getText().equals("day")
                &&!timeTextField.getText().equals("evening")  && !timeTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "the time could just be set as morning, day or evening!","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        /*
        int idnumber = Integer.parseInt(flightNumberTextField.getText());
        String departure = departureTextField.getText();
        String destination = arrivalTextField.getText();
        String time = timeTextField.getText();
        int date = Integer.parseInt(dateTextField.getText());
        */
        
        ArrayList <Flight> searchResult = new ArrayList <> ();
        
        for (AirLine al : travelagency.getAirlineList()) {
            for (Flight fl : al.getFlightSchedule()) {
                
                if ( ( flightNumberTextField.getText().isEmpty() || fl.getIdNumber() == Integer.parseInt(flightNumberTextField.getText()) ) 
                        && ( fl.getDeparture().equals( departureTextField.getText()) ) 
                        && ( fl.getDestination().equals( arrivalTextField.getText()) ) 
                        && ( timeTextField.getText().isEmpty() || fl.getAroundTime().equals(timeTextField.getText()) ) 
                        && ( dateTextField.getText().isEmpty() || fl.getDepDate() == Integer.parseInt(dateTextField.getText()) ) ) {
                    
                    searchResult.add(fl);
                    
                }
            }
        }
        
        if ( searchResult.isEmpty() ) {
            JOptionPane.showMessageDialog(null, "There is no flight satisfying your need!");
            return;
        }
        MeetConditionJPanel mcJP = new MeetConditionJPanel( travelagency, container, searchResult);
        container.add("MeetConditionJPanel", mcJP);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
        
    }//GEN-LAST:event_searchBtnActionPerformed

    private void allBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allBtnActionPerformed
        // TODO add your handling code here:
        MasterFlightScheduleJPanel mfsJP = new MasterFlightScheduleJPanel(travelagency, container);
        container.add("MasterFlightScheduleJPanel", mfsJP) ;
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_allBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allBtn;
    private javax.swing.JTextField arrivalTextField;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JTextField departureTextField;
    private javax.swing.JTextField flightNumberTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField timeTextField;
    // End of variables declaration//GEN-END:variables
}
