/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.customer;
import Business.*;
import javax.swing.JPanel;
import java.awt.CardLayout;
/**
 *
 * @author xutao
 */
public class ViewFlightJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewFlightJPanel
     */
    
    private Flight flight = new Flight();
    private JPanel container = new JPanel();
    public ViewFlightJPanel( Flight flight, JPanel container) {
        initComponents();
        this.flight = flight;
        this.container = container;
        Display();
    }
    
    public void Display() {
        idTextField.setText(String.valueOf(flight.getIdNumber()));
        departureTextField.setText(flight.getDeparture());
        destinationTextField.setText(flight.getDestination());
        serialTextField.setText(String.valueOf(flight.getAirplane().getSerialNumber()));
        seatTextField.setText(String.valueOf(flight.getSeat().getAvailNum()));
        
        int date = flight.getDepDate();
        int yy = date / 10000;
        int mm = date / 100 - yy * 100;
        int dd = date - yy * 10000 - mm * 100;
        String yyString;
        String mmString;
        String ddString;
        if( yy / 10 == 0)
            yyString = "0" + String.valueOf(yy);
        else
            yyString = String.valueOf(yy);
        if( mm / 10 == 0)
            mmString = "0" + String.valueOf(mm);
        else
             mmString = String.valueOf(mm);
        if( dd / 10 == 0)
            ddString = "0" + String.valueOf(dd);
        else
            ddString = String.valueOf(dd);
        String dateString = yyString + "/" + mmString + "/" + ddString;
        depDateTextField.setText(dateString);
        int time = flight.getDepTime();
        int hh = time / 100;
        int mi = time - hh * 100;
        String hhString;
        String miString;
        if( hh / 10 == 0)
            hhString = "0" + String.valueOf(hh);
        else
            hhString = String.valueOf(hh);
        if( mi / 10 == 0)
            miString = "0" + String.valueOf(mi);
        else
            miString = String.valueOf(mi);
        String timeString = hhString + ":" + miString;
        depTimeTextField.setText(timeString);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        seatTextField = new javax.swing.JTextField();
        serialTextField = new javax.swing.JTextField();
        depTimeTextField = new javax.swing.JTextField();
        depDateTextField = new javax.swing.JTextField();
        destinationTextField = new javax.swing.JTextField();
        departureTextField = new javax.swing.JTextField();
        idTextField = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("View Flight");

        jLabel2.setText("ID Number :");

        jLabel3.setText("Departure ;");

        jLabel4.setText("Destination :");

        jLabel5.setText("Departure Date :");

        jLabel6.setText("Departure Time :");

        jLabel7.setText("Airplane Serial :");

        jLabel8.setText("Available Seat Quantity :");

        seatTextField.setEditable(false);
        seatTextField.setEnabled(false);

        serialTextField.setEditable(false);
        serialTextField.setEnabled(false);

        depTimeTextField.setEditable(false);
        depTimeTextField.setEnabled(false);

        depDateTextField.setEditable(false);
        depDateTextField.setEnabled(false);

        destinationTextField.setEditable(false);
        destinationTextField.setEnabled(false);

        departureTextField.setEditable(false);
        departureTextField.setEnabled(false);

        idTextField.setEditable(false);
        idTextField.setEnabled(false);

        backBtn.setText("< < back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(backBtn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idTextField)
                            .addComponent(departureTextField)
                            .addComponent(destinationTextField)
                            .addComponent(depDateTextField)
                            .addComponent(depTimeTextField)
                            .addComponent(serialTextField)
                            .addComponent(seatTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(departureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(destinationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(depDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(depTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(serialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(seatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(backBtn)
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField depDateTextField;
    private javax.swing.JTextField depTimeTextField;
    private javax.swing.JTextField departureTextField;
    private javax.swing.JTextField destinationTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField seatTextField;
    private javax.swing.JTextField serialTextField;
    // End of variables declaration//GEN-END:variables
}
