/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;
import Music.Singer;
import Music.Song;
import MusicEcosystem.*;
import MusicEcosystem.DB4OUtil.DB4OUtil;
import MusicEcosystem.Enterprise.Enterprise;
import MusicEcosystem.Network.Network;
import MusicEcosystem.Organization.Organization;
import MusicEcosystem.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author liwen
 */
public class MainJframe extends javax.swing.JFrame {

    /**
     * Creates new form MainJframe
     */
    
    private Ecosystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public MainJframe() throws FileNotFoundException, IOException {
        initComponents();
        this.setSize(995,511);
        //475,496
        logoutBtn.setEnabled(false);
        system = dB4OUtil.retrieveSystem();
        if (system.getSongcount() != 0)
            Song.count = system.getSongcount();
        if (system.getSingercount() != 0)
            Singer.count =  system.getSingercount();
        if (system.getAccountNum() != 0) {
            UserAccount.count = system.getAccountNum();
        }
        //System.out.println(system.getWorkQueue());
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
            super.windowClosing(e);
            System.out.println("wondow closed.");
            system.setSongcount(Song.count);
            system.setSingercount(Singer.count);
            system.setAccountNum(UserAccount.count);
            dB4OUtil.storeSystem(system);
            }
            
        });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JButton();
        userNameTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        passWordTxt = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        container = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(855, 516));

        jSplitPane2.setPreferredSize(new java.awt.Dimension(855, 515));

        jPanel2.setBackground(new java.awt.Color(196, 171, 238));

        logoutBtn.setBackground(new java.awt.Color(255, 255, 255));
        logoutBtn.setText("Log out");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setText("User Name :");

        jLabel2.setText("Password :");

        loginBtn.setText("Log in");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(userNameTxt)
                    .addComponent(passWordTxt)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(loginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passWordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(loginBtn)
                .addGap(18, 18, 18)
                .addComponent(logoutBtn)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(jPanel2);

        container.setBackground(new java.awt.Color(217, 220, 242));
        container.setLayout(new java.awt.CardLayout());
        jSplitPane2.setRightComponent(container);

        getContentPane().add(jSplitPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    
    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        userNameTxt.setEditable(true);
        userNameTxt.setEnabled(true);
        passWordTxt.setEnabled(true);
        passWordTxt.setEditable(true);
        loginBtn.setEnabled(true);
        logoutBtn.setEnabled(false);
        userNameTxt.setText("");
        passWordTxt.setText("");
        container.removeAll();
        JPanel jpanel = new JPanel();
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("new JPanel", jpanel);
        layout.next(container);
        system.setSongcount(Song.count);
        system.setSingercount(Singer.count);
        system.setAccountNum(UserAccount.count);
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        String userName = userNameTxt.getText();
        char[] passwordCharArray = passWordTxt.getPassword();
        String passWord = String.valueOf(passwordCharArray);
        
        UserAccount userAccount = system.getUserAccountDirectory().checkUserNamePwd(userName, passWord);
        
        Organization organization = null;
        Enterprise enterprise = null;
        Network network = null;
        
        if(userAccount == null) {
            for (Network nt : system.getNetworkList()) {
                userAccount = nt.getUserAccountDirectory().checkUserNamePwd(userName, passWord);
                if (userAccount == null) {
                    for (Enterprise ep : nt.getEnterpriseDirectory().getEnterpaiseList() ) {
                        userAccount = ep.getUserAccountDirectory().checkUserNamePwd(userName, passWord);
                        if (userAccount == null) {
                          for (Organization og : ep.getOrganizationDirectory().getOrganizationList()) {
                            userAccount = og.getUserAccountDirectory().checkUserNamePwd(userName, passWord);
                                if (userAccount != null) {
                                    enterprise = ep;
                                    organization = og;
                                    network = nt;
                                    break;
                                }
                            }
                        }
                        else {
                            enterprise = ep;
                            network = nt;
                            break;
                        }
                    
                        if (organization != null) {
                            break;
                        }
                    }
                }
                else {
                    network = nt;
                    break;
                }
                if ( enterprise != null ) {
                    break;
                }
            }
        }
        
        if (userAccount == null) {
            JOptionPane.showMessageDialog(null, "Please input valid username and password!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        else{
            CardLayout layout = (CardLayout) container.getLayout();
            container.add("WorkArea", userAccount.getRole().createWorkArea(container, userAccount, organization, enterprise, network,system));
            layout.next(container);
        }
        userNameTxt.setEditable(false);
        userNameTxt.setEnabled(false);
        passWordTxt.setEnabled(false);
        passWordTxt.setEditable(false);
        loginBtn.setEnabled(false);
        logoutBtn.setEnabled(true);
    }//GEN-LAST:event_loginBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainJframe mainJframe = null;
                try {
                    mainJframe = new MainJframe();
                } catch (IOException ex) {
                    Logger.getLogger(MainJframe.class.getName()).log(Level.SEVERE, null, ex);
                }
                mainJframe.setVisible(true);
                mainJframe.getRootPane().setDefaultButton(mainJframe.loginBtn);
                
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPasswordField passWordTxt;
    private javax.swing.JTextField userNameTxt;
    // End of variables declaration//GEN-END:variables
}
