/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Administrator;
import Business.*;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author xutao
 */
public class ViewFlightJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewFlightJPanel
     */
    
    Flight flight = new Flight();
    JPanel container = new JPanel();
    Customer customer = new Customer();
    
    public ViewFlightJPanel( Flight flight, JPanel container, Customer customer) {
        initComponents();
        this.flight = flight;
        this.container = container;
        this.customer = customer;
        Display();
    }
    
    public void Display () {
        flightIDnumTextField.setText(String.valueOf(flight.getIdNumber()));
        dapartureTextField.setText(flight.getDeparture());
        destinationTextField.setText(flight.getDestination());
        int yy = flight.getDepDate() / 10000;
        int mm = flight.getDepDate() / 100 - yy *100;
        int dd = flight.getDepDate() - yy * 10000 - mm * 100;
        String date;
        date = String.valueOf(yy) + "/" + String.valueOf(mm) + "/" + String.valueOf(dd);
        departureDateTextField.setText(date);
        int h = flight.getDepTime() / 100;
        int m = flight.getDepTime() - h * 100;
        String time;
        time = String.valueOf(h) + ":" + String.valueOf(m);
        departureTimeTextField.setText(time);
        serialNumTextField.setText(String.valueOf(flight.getAirplane().getSerialNumber()));
        String seat;
        seat = "[" + String.valueOf(customer.getSeat()[0]) + "," + String.valueOf(customer.getSeat()[1]) + "]";
        seatTextField.setText(seat);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        serialNumTextField = new javax.swing.JTextField();
        flightIDnumTextField = new javax.swing.JTextField();
        dapartureTextField = new javax.swing.JTextField();
        destinationTextField = new javax.swing.JTextField();
        departureDateTextField = new javax.swing.JTextField();
        departureTimeTextField = new javax.swing.JTextField();
        seatTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Customer' s Order Details");

        jLabel2.setText("Flight IDnum :");

        jLabel3.setText("Departure :");

        jLabel4.setText("Destination :");

        jLabel5.setText("Departure Date :");

        jLabel6.setText("Departure Time :");

        jLabel7.setText("Plane Serial Num :");

        jLabel8.setText("Seat :");

        serialNumTextField.setEditable(false);
        serialNumTextField.setEnabled(false);

        flightIDnumTextField.setEditable(false);
        flightIDnumTextField.setEnabled(false);

        dapartureTextField.setEditable(false);
        dapartureTextField.setEnabled(false);

        destinationTextField.setEditable(false);
        destinationTextField.setEnabled(false);

        departureDateTextField.setEditable(false);
        departureDateTextField.setEnabled(false);

        departureTimeTextField.setEditable(false);
        departureTimeTextField.setEnabled(false);

        seatTextField.setEditable(false);
        seatTextField.setEnabled(false);

        jButton1.setText("< < back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jButton1))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(flightIDnumTextField)
                            .addComponent(dapartureTextField)
                            .addComponent(destinationTextField)
                            .addComponent(departureDateTextField)
                            .addComponent(departureTimeTextField)
                            .addComponent(serialNumTextField)
                            .addComponent(seatTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE))))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(flightIDnumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dapartureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(destinationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(departureDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(departureTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(serialNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(seatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dapartureTextField;
    private javax.swing.JTextField departureDateTextField;
    private javax.swing.JTextField departureTimeTextField;
    private javax.swing.JTextField destinationTextField;
    private javax.swing.JTextField flightIDnumTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField seatTextField;
    private javax.swing.JTextField serialNumTextField;
    // End of variables declaration//GEN-END:variables
}
