/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.UserAdmin;

import MusicEcosystem.UserAccount.CustomerAccount;
import MusicEcosystem.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import jdk.nashorn.internal.parser.TokenType;

/**
 *
 * @author liwen
 */
public class ViewUserDetail extends javax.swing.JPanel {

    /**
     * Creates new form ViewUserDetail
     */
    JPanel container;
    private UserAccount ua;
    
    public ViewUserDetail(JPanel container,UserAccount ua) {
        initComponents();
        this.container=container;
        this.ua=ua;
        populate();
        populateCbx();
        title.setText("Account name : " + ua.getRole());
        title.setHorizontalAlignment(SwingConstants.CENTER);
         
    }
    
    public void populate() {
        nameTxt.setText(ua.getUserName());
        pwdTxt.setText(ua.getUserPwd());
        roleTxt.setText( String.valueOf(ua.getRole()) );
        IDtxt.setText(String.valueOf(ua.getId()));
        
        nameTxt.setEnabled(false);
        nameTxt.setEditable(false);
        pwdTxt.setEnabled(false);
        pwdTxt.setEditable(false);
        roleTxt.setEnabled(false);
        roleTxt.setEditable(false);
        IDtxt.setEnabled(false);
        IDtxt.setEditable(false);
        UpdateBtn.setEnabled(true);
        saveBtn.setEnabled(false);
        
    }
    
    public void populateCbx( ) {
        vipCbx.removeAllItems();
        if (ua instanceof CustomerAccount) {
            vipCbx.addItem("VIP");
            vipCbx.addItem("No VIP");
            if (((CustomerAccount)ua).isVip()) {
                vipCbx.setSelectedItem("VIP");
            }
            else
                vipCbx.setSelectedItem("No VIP");
        }
        else 
        {
            vipCbx.addItem("");
        }
        vipCbx.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        pwdTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        UpdateBtn = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        roleTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        IDtxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        vipCbx = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(217, 220, 242));

        jLabel1.setText("User Name");

        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });

        jLabel2.setText("Password");

        UpdateBtn.setText("Update");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        title.setBackground(new java.awt.Color(217, 220, 242));
        title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        title.setText("<account>");
        title.setMaximumSize(new java.awt.Dimension(200, 22));

        backBtn.setText("< < back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("Role");

        jLabel4.setText("ID");

        jLabel6.setText("VIP :");

        vipCbx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(UpdateBtn)
                                .addGap(18, 18, 18)
                                .addComponent(saveBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameTxt)
                                    .addComponent(pwdTxt)
                                    .addComponent(roleTxt)
                                    .addComponent(IDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vipCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(backBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pwdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(roleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(IDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(vipCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(UpdateBtn))
                .addGap(59, 59, 59)
                .addComponent(backBtn)
                .addGap(44, 44, 44))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        // TODO add your handling code here:
        nameTxt.setEnabled(true);
        nameTxt.setEditable(true);
        pwdTxt.setEnabled(true);
        pwdTxt.setEditable(true);
        if (ua instanceof CustomerAccount) {
            vipCbx.setEnabled(true);
        }
        UpdateBtn.setEnabled(false);
        saveBtn.setEnabled(true);
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout)container.getLayout();
        layout.previous(container);
        Component[] components = container.getComponents();
        for (Component cp : components) {
            if (cp instanceof OverAllUser) {
                ((OverAllUser) cp).refreshTable();
            }
        } 
    }//GEN-LAST:event_backBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        if (nameTxt.getText().equals("") || pwdTxt.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "the account name and password can't be empty!");
            return;
        }
        if (ua instanceof CustomerAccount) {
            CustomerAccount ca = (CustomerAccount) ua;
            if (vipCbx.getSelectedItem().equals("VIP"))
                ca.setVip(true);
            else 
                ca.setVip(false);
            }
            
        ua.setUserPwd(pwdTxt.getText());
        ua.setUserName(nameTxt.getText());   
        JOptionPane.showMessageDialog(null, "Updated successfully");  
        populate();
        vipCbx.setEnabled(false);
    }//GEN-LAST:event_saveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDtxt;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField pwdTxt;
    private javax.swing.JTextField roleTxt;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel title;
    private javax.swing.JComboBox vipCbx;
    // End of variables declaration//GEN-END:variables
}
