/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.RecordCompany;


import MusicEcosystem.Ecosystem;
import MusicEcosystem.Network.Network;
import MusicEcosystem.Organization.RecordCompanyOrganization;
import MusicEcosystem.UserAccount.UserAccount;

//import UserInterface.Admin.adminSinger;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author liwen
 */
public class ManageArea2 extends javax.swing.JPanel {

    /**
     * Creates new form ManageArea
     */
    JPanel container;
    RecordCompanyOrganization recordCompanyOrganization;
    UserAccount account;
    private Network network;
    public ManageArea2(JPanel container,RecordCompanyOrganization recordCompanyOrganization, UserAccount account, Network network) {
        initComponents();
        this.container = container;
        this.recordCompanyOrganization = recordCompanyOrganization;
        this.account = account;
        this.network = network;
        this.setSize(630, 511);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageSongbtn = new javax.swing.JButton();
        manageSingerBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(217, 220, 242));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setVerifyInputWhenFocusTarget(false);

        manageSongbtn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        manageSongbtn.setText("Manage Songs");
        manageSongbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageSongbtnActionPerformed(evt);
            }
        });

        manageSingerBtn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        manageSingerBtn.setText("Manage Singers ");
        manageSingerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageSingerBtnActionPerformed(evt);
            }
        });

        jButton2.setText("<<back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Record Company Enterprise Manage Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(manageSongbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageSingerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jButton2)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addGap(73, 73, 73)
                .addComponent(manageSongbtn)
                .addGap(18, 18, 18)
                .addComponent(manageSingerBtn)
                .addGap(161, 161, 161)
                .addComponent(jButton2)
                .addGap(62, 62, 62))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageSongbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageSongbtnActionPerformed
        // TODO add your handling code here:
//        SongDirectory sd=
        MusicLibrary musicLibrary = new MusicLibrary(container, recordCompanyOrganization, account, network);
        container.add("musicLibrary", musicLibrary);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
        
        
    }//GEN-LAST:event_manageSongbtnActionPerformed

    private void manageSingerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageSingerBtnActionPerformed
        // TODO add your handling code here:
        SingerList sl = new SingerList(container,recordCompanyOrganization);
        container.add("sl", sl);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_manageSingerBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageSingerBtn;
    private javax.swing.JButton manageSongbtn;
    // End of variables declaration//GEN-END:variables
}
