/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.RecordCompany;

import Music.*;
import MusicEcosystem.Organization.RecordCompanyOrganization;
import MusicEcosystem.Organization.SongOrganization;
import java.awt.*;
import java.util.Iterator;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author liwen
 */
public class SingerList extends javax.swing.JPanel {
    //JPanel container;
    private SingerDirectory singerDirectory;
    private JPanel container;
    private SongDirectory songDirectory;
    /**
     * Creates new form Singer
     */
    public SingerList(JPanel container, RecordCompanyOrganization recordCompanyOrganization) {
        initComponents();
        this.container=container;
        this.singerDirectory = recordCompanyOrganization.getSingerDirectory();
        this.songDirectory = recordCompanyOrganization.getSongDirectory();
        this.setSize(630, 511);
        refreshTable();
    }
    
    public void refreshTable() {
        int rowCount = singerListTbl.getRowCount();
        DefaultTableModel model = (DefaultTableModel)singerListTbl.getModel();
        for(int i = rowCount - 1; i >=0; i--) {
            model.removeRow(i);
        }
        
        for(Singer singer : singerDirectory.getSingerList()) {
            Object row[] = new Object[2];
            row[0] = singer;//why
            row[1] = singer.getId();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        singerListTbl = new javax.swing.JTable();
        singerListViewBtn = new javax.swing.JButton();
        singerListDeleteBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(217, 220, 242));
        setPreferredSize(new java.awt.Dimension(630, 511));

        singerListTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Singer Name", "Singer ID"
            }
        ));
        jScrollPane1.setViewportView(singerListTbl);

        singerListViewBtn.setText("View Details");
        singerListViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singerListViewBtnActionPerformed(evt);
            }
        });

        singerListDeleteBtn.setText("Delete");
        singerListDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singerListDeleteBtnActionPerformed(evt);
            }
        });

        backBtn.setText("< < back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("All Singer Directory");

        addBtn.setText("Add Singer");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(singerListViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(singerListDeleteBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(backBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(singerListDeleteBtn)
                    .addComponent(singerListViewBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addBtn)
                .addGap(79, 79, 79)
                .addComponent(backBtn)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void singerListDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singerListDeleteBtnActionPerformed
        // TODO add your handling code here:
        int row = singerListTbl.getSelectedRow();

        if(row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Singer singer = (Singer)singerListTbl.getValueAt(row, 0);
        int singerId = singer.getId();
        
        singerDirectory.RemoveSinger(singer.getId());
        Iterator <Song> iterator = songDirectory.getSongList().iterator();
        while (iterator.hasNext()) {
            Song song = iterator.next();
            if (song.getSingerid() == singerId) {
                iterator.remove();
            }
        }
        refreshTable();
    }//GEN-LAST:event_singerListDeleteBtnActionPerformed

    private void singerListViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singerListViewBtnActionPerformed
        // TODO add your handling code here:
        int row = singerListTbl.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Singer singer = (Singer)singerListTbl.getValueAt(row, 0);
        SingerDetails sd = new SingerDetails(container, singer);
        container.add("SingerDetails", sd);
        CardLayout layout = (CardLayout)container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_singerListViewBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout cardLayout = (CardLayout) container.getLayout();
        cardLayout.previous(container);
    }//GEN-LAST:event_backBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        AddSinger asJP = new AddSinger(container, singerDirectory);
        container.add("AddSinger", asJP);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_addBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton singerListDeleteBtn;
    private javax.swing.JTable singerListTbl;
    private javax.swing.JButton singerListViewBtn;
    // End of variables declaration//GEN-END:variables
}
