/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.RecordCompany;

import Music.*;
import MusicEcosystem.Ecosystem;
import MusicEcosystem.Network.Network;
import MusicEcosystem.Organization.RecordCompanyOrganization;
import MusicEcosystem.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author xutao
 */
public class SongDetail extends javax.swing.JPanel {

    /**
     * Creates new form SongDetail
     */
    JPanel container;
    Song song;
    private UserAccount account ;
    private Network network;
    private SingerDirectory singerDirectory;
    public SongDetail(JPanel container, Song song, RecordCompanyOrganization recordCompanyOrganization, UserAccount account, Network network) {
        initComponents();
        this.container = container;
        this.song = song;
        this.singerDirectory = recordCompanyOrganization.getSingerDirectory();
        this.account = account;
        this.network = network;
        this.setSize(630, 511);
        Populate();
        
        songNameTxt.setEnabled(false);
        songNameTxt.setEditable(false);
        idTxt.setEnabled(false);
        idTxt.setEditable(false);
        timeTxt.setEnabled(false);
        timeTxt.setEditable(false);
        singerNameTxt.setEnabled(false);
        singerNameTxt.setEditable(false);
        albumTxt.setEnabled(false);
        albumTxt.setEditable(false);
        singerIdTxt.setEnabled(false);
        singerIdTxt.setEditable(false);
        updateBtn.setEnabled(true);
        SaveBtn.setEnabled(false);
    }

    public void Populate() {
        songNameTxt.setText(song.getName());
        idTxt.setText(String.valueOf(song.getId()));
        timeTxt.setText(song.getTime());
        singerNameTxt.setText(song.getSinger());
        singerIdTxt.setText(String.valueOf(song.getSingerid()));
        albumTxt.setText(song.getAlbum());

        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        songNameTxt = new javax.swing.JTextField();
        idTxt = new javax.swing.JTextField();
        timeTxt = new javax.swing.JTextField();
        singerNameTxt = new javax.swing.JTextField();
        albumTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        SaveBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        singerIdTxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(217, 220, 242));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Song Details");

        jLabel2.setText("Song Name :");

        jLabel3.setText("Song ID : ");

        jLabel4.setText("Time :");

        jLabel5.setText("Singer Name :");

        jLabel6.setText("Album :");

        songNameTxt.setEditable(false);
        songNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                songNameTxtActionPerformed(evt);
            }
        });

        idTxt.setEditable(false);

        timeTxt.setEditable(false);

        singerNameTxt.setEditable(false);

        albumTxt.setEditable(false);

        jButton1.setText("< < back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Singer ID :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel7)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(22, 22, 22)))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(singerNameTxt)
                            .addComponent(albumTxt)
                            .addComponent(singerIdTxt)
                            .addComponent(songNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                            .addComponent(timeTxt)
                            .addComponent(idTxt)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(380, Short.MAX_VALUE)
                        .addComponent(updateBtn)
                        .addGap(18, 18, 18)
                        .addComponent(SaveBtn)))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(songNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(singerNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(singerIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(albumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn)
                    .addComponent(SaveBtn))
                .addGap(53, 53, 53)
                .addComponent(jButton1)
                .addGap(55, 55, 55))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
        
        Component [] components = container.getComponents();
        for ( Component cp : components ) {
            if (cp instanceof MusicLibrary) {
                MusicLibrary ml = (MusicLibrary) cp;
                ml.refreshTable();
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
        try {
            Integer.parseInt(idTxt.getText());
            Integer.parseInt(singerIdTxt.getText());
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "the song Id and singer Id must be Integer");
            return;
        }
        
        String singername = singerDirectory.getNameFromeID( Integer.parseInt(singerIdTxt.getText()) );
        if(singername == null) {
            JOptionPane.showMessageDialog(null, "No such a singer, please add the singer first or correct to a right singer!", 
                    "Warning", JOptionPane.WARNING_MESSAGE);
            Populate();
            songNameTxt.setEnabled(false);
            songNameTxt.setEditable(false);
            timeTxt.setEnabled(false);
            timeTxt.setEditable(false);
            singerNameTxt.setEnabled(false);
            singerNameTxt.setEditable(false);
            albumTxt.setEnabled(false);
            albumTxt.setEditable(false);
            singerIdTxt.setEnabled(false);
            singerIdTxt.setEditable(false);
            updateBtn.setEnabled(true);
            SaveBtn.setEnabled(false);
            return;
        }
        
        song.setId(Integer.parseInt(idTxt.getText()));
        song.setName(songNameTxt.getText());
        song.setTime(timeTxt.getText());
        song.setSinger(singername);
        song.setSingerid(Integer.parseInt(singerIdTxt.getText()));
        song.setAlbum(albumTxt.getText());
        Populate();
        
        
        
        songNameTxt.setEnabled(false);
        songNameTxt.setEditable(false);
        idTxt.setEnabled(false);
        idTxt.setEditable(false);
        timeTxt.setEnabled(false);
        timeTxt.setEditable(false);
        singerNameTxt.setEnabled(false);
        singerNameTxt.setEditable(false);
        albumTxt.setEnabled(false);
        albumTxt.setEditable(false);
        singerIdTxt.setEnabled(false);
        singerIdTxt.setEditable(false);
        updateBtn.setEnabled(true);
        SaveBtn.setEnabled(false);
        
        int choose = JOptionPane.showConfirmDialog(null, "So you want to send change song request to musicPlatForm?", 
                "", JOptionPane.YES_NO_OPTION);
        
        if (choose == JOptionPane.YES_OPTION) {
            SendChangeRequest scrJP = new SendChangeRequest(container, Integer.parseInt(idTxt.getText()), account, network);
            container.add("SendChangeRequest", scrJP);
            CardLayout layout = (CardLayout) container.getLayout();
            layout.next(container);
        }
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void songNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_songNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_songNameTxtActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        songNameTxt.setEnabled(true);
        songNameTxt.setEditable(true);
        timeTxt.setEnabled(true);
        timeTxt.setEditable(true);
        singerIdTxt.setEnabled(true);
        singerIdTxt.setEditable(true);
        albumTxt.setEnabled(true);
        albumTxt.setEditable(true);
        updateBtn.setEnabled(false);
        SaveBtn.setEnabled(true);
   
    }//GEN-LAST:event_updateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaveBtn;
    private javax.swing.JTextField albumTxt;
    private javax.swing.JTextField idTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField singerIdTxt;
    private javax.swing.JTextField singerNameTxt;
    private javax.swing.JTextField songNameTxt;
    private javax.swing.JTextField timeTxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
