/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.songAdmin;

import Music.Song;
import MusicEcosystem.Enterprise.Enterprise;
import MusicEcosystem.Enterprise.MusicPlatEnterprise;
import MusicEcosystem.Enterprise.RecordCompanyEnterprise;
import MusicEcosystem.Network.Network;
import MusicEcosystem.Organization.Organization;
import MusicEcosystem.Organization.SongOrganization;
import MusicEcosystem.UserAccount.UserAccount;
import WorkQueue.AddSongRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xutao
 */
public class AddSongRequestArea extends javax.swing.JPanel {

    /**
     * Creates new form AddSongRequestArea
     */
    JPanel container;
    UserAccount sender;
    private SongOrganization songOrganization;
    private MusicPlatEnterprise musicPlatEnterprise;
    private Network network;
    public AddSongRequestArea(JPanel container, UserAccount sender,SongOrganization songOrganization, MusicPlatEnterprise enterprise, Network network) {
        initComponents();
        this.container = container;
        this.sender = sender;
        this.songOrganization = songOrganization;
        this.musicPlatEnterprise = enterprise;
        this.network = network;
        this.setSize(630, 511);
        title.setHorizontalAlignment(SwingConstants.CENTER);
        populateTbl();
    }

    
    public void populateTbl () {
        int rowCount = songTbl.getRowCount();
        DefaultTableModel model = (DefaultTableModel) songTbl.getModel();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        for (Enterprise ep : network.getEnterpriseDirectory().getEnterpaiseList()) {
            if (ep instanceof RecordCompanyEnterprise) {
                for (Organization og : ep.getOrganizationDirectory().getOrganizationList()) {
                    for (Song song : og.getSongDirectory().getSongList()) {
                        Object[] row = new Object[3];
                        row[0] = song;
                        row[1] = song.getId();
                        row[2] = song.getSinger();
                        model.addRow(row);
                    }
                }
                return;
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        songIdTxt = new javax.swing.JTextField();
        sendBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        songTbl = new javax.swing.JTable();

        setBackground(new java.awt.Color(217, 220, 242));

        title.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        title.setText("Add Song Request Work Area");

        jLabel2.setText("Song ID :");

        sendBtn.setText("Send");
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });

        backBtn.setText("< < back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("< send Request to Record Company to add a Song >");

        songTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Song name", "Song ID", "Singer name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(songTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(backBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(title)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(songIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(title)
                .addGap(40, 40, 40)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendBtn)
                    .addComponent(songIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(56, 56, 56)
                .addComponent(backBtn)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backBtnActionPerformed

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        // TODO add your handling code here:
        RecordCompanyEnterprise recordCompany = null;
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpaiseList()) {
            if(enterprise instanceof RecordCompanyEnterprise) {
                recordCompany = (RecordCompanyEnterprise)enterprise;
                break;
            }
        }
        if (recordCompany == null) {
            JOptionPane.showMessageDialog(null, "No Record Company !", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            Integer.parseInt(songIdTxt.getText());
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "The SongId must be Integer! ", "Warnint", JOptionPane.WARNING_MESSAGE);
            songIdTxt.setText("");
            return;
        }
        AddSongRequest addSongRequest = new AddSongRequest(musicPlatEnterprise, sender, recordCompany, "Add A Song. ", Integer.parseInt(songIdTxt.getText()));
        network.getWorkQueue().AddWorkrequest(addSongRequest);
        JOptionPane.showMessageDialog(null, "Work Request send successfully");
        songIdTxt.setText("");
    }//GEN-LAST:event_sendBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sendBtn;
    private javax.swing.JTextField songIdTxt;
    private javax.swing.JTable songTbl;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
