/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.songAdmin;

import MusicEcosystem.Enterprise.Enterprise;
import MusicEcosystem.Enterprise.MusicPlatEnterprise;
import MusicEcosystem.Network.Network;
import MusicEcosystem.Organization.SongOrganization;
import MusicEcosystem.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author xutao
 */
public class SongManagerWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form SongManagerWorkArea
     */
    JPanel container;
    SongOrganization songOrganization;
    UserAccount account;
    MusicPlatEnterprise musicPlatEnterprise;
    private Network network;
    public SongManagerWorkArea(JPanel container, SongOrganization songOrganization, Enterprise enterprise, UserAccount account, Network network) {
        initComponents();
        this.container = container;
        this.songOrganization = songOrganization;
        this.account = account;
        this.musicPlatEnterprise = (MusicPlatEnterprise) enterprise;
        this.network = network;
        this.setSize(630, 511);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        maSongBtn = new javax.swing.JButton();
        opWorkQueueBtn = new javax.swing.JButton();
        requestBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(217, 220, 242));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Song Manager Work Area");

        maSongBtn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        maSongBtn.setText("Manage Songs");
        maSongBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maSongBtnActionPerformed(evt);
            }
        });

        opWorkQueueBtn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        opWorkQueueBtn.setText("Option Work Queue");
        opWorkQueueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opWorkQueueBtnActionPerformed(evt);
            }
        });

        requestBtn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        requestBtn.setText("Add Song Request");
        requestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(maSongBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(opWorkQueueBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(requestBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(76, 76, 76)
                .addComponent(maSongBtn)
                .addGap(27, 27, 27)
                .addComponent(opWorkQueueBtn)
                .addGap(27, 27, 27)
                .addComponent(requestBtn)
                .addContainerGap(223, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void maSongBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maSongBtnActionPerformed
        // TODO add your handling code here:
        OverAllSong ovsJP = new OverAllSong(container, songOrganization.getSongDirectory());
        container.add("OverAllSong", ovsJP);
        CardLayout layout = (CardLayout)container.getLayout();
        layout.next(container);
        
    }//GEN-LAST:event_maSongBtnActionPerformed

    private void opWorkQueueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opWorkQueueBtnActionPerformed
        // TODO add your handling code here:
        SongManageWorkQueueArea smwqaJP = new SongManageWorkQueueArea(container, network.getWorkQueue(),songOrganization);
        container.add("SongManageWorkQueueArea",smwqaJP);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
        
    }//GEN-LAST:event_opWorkQueueBtnActionPerformed

    private void requestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestBtnActionPerformed
        // TODO add your handling code here:
        AddSongRequestArea asrJP = new AddSongRequestArea(container, account, songOrganization,musicPlatEnterprise, network);
        container.add("AddSongRequest", asrJP);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_requestBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton maSongBtn;
    private javax.swing.JButton opWorkQueueBtn;
    private javax.swing.JButton requestBtn;
    // End of variables declaration//GEN-END:variables
}
