/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerArea;

import Music.SongDirectory;
import MusicEcosystem.Enterprise.MusicPlatEnterprise;
import MusicEcosystem.Organization.CustomerOrganization;
import MusicEcosystem.Organization.Organization;
import MusicEcosystem.Organization.SongOrganization;
import MusicEcosystem.UserAccount.CustomerAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author liwen
 */
public class CustomerMainArea extends javax.swing.JPanel {

    /**
     * Creates new form CustomerMainArea
     */
    JPanel container;
    private CustomerAccount account;
    private SongDirectory songDirectory;
    private CustomerOrganization customerOrganization;
    public CustomerMainArea(JPanel container,CustomerAccount account, MusicPlatEnterprise musicPlatEnterprise) {
        initComponents();
        this.container = container;
        this.account = account;
        for ( Organization og : musicPlatEnterprise.getOrganizationDirectory().getOrganizationList()) {
            if (og instanceof SongOrganization) {
                this.songDirectory = og.getSongDirectory();
            }
            if (og instanceof  CustomerOrganization) {
                this.customerOrganization = (CustomerOrganization) og;
            }
        }
       this.setSize(630, 511);
       if (account.isVip()) {
           VIPTxt.setText("< You are VIP >");
           
       }
       else
           VIPTxt.setText("< You are unVIP >");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AllSongBtn = new javax.swing.JButton();
        MySongListBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        VIPTxt = new javax.swing.JLabel();

        setBackground(new java.awt.Color(217, 220, 242));

        AllSongBtn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        AllSongBtn.setText("View All Songs");
        AllSongBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllSongBtnActionPerformed(evt);
            }
        });

        MySongListBtn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        MySongListBtn.setText("My SongList");
        MySongListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MySongListBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Welcome to Bomb Music");

        VIPTxt.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        VIPTxt.setText("<VIP>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AllSongBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(MySongListBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel1)
                .addContainerGap(177, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(VIPTxt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(VIPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AllSongBtn)
                .addGap(36, 36, 36)
                .addComponent(MySongListBtn)
                .addContainerGap(232, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AllSongBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllSongBtnActionPerformed
        // TODO add your handling code here:
        ViewSongAddSong vas = new ViewSongAddSong(container, songDirectory, account, "Song Library");
        container.add("ViewAllSong_pt", vas);
        CardLayout layout = (CardLayout)container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_AllSongBtnActionPerformed

    private void MySongListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MySongListBtnActionPerformed
       // TODO add your handling code here:
       SongList slJP = new SongList(container, account, customerOrganization);
       container.add("SongList", slJP);
       CardLayout layout = (CardLayout) container.getLayout();
       layout.next(container);
    }//GEN-LAST:event_MySongListBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AllSongBtn;
    private javax.swing.JButton MySongListBtn;
    private javax.swing.JLabel VIPTxt;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
